spring:
  application:
    name: TasksAPI

  profiles:
    active: dev

  # Mysql
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_HOST}/task_api
    username: root
    password: ${DB_PASSWORD}

  # Mostrar queries en la BD, no recommend to production
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

# Not show stack-trace unauthorized accesses in the API
server:
  error:
    include-stacktrace: never