CREATE TABLE IF NOT EXISTS users(
    id BIGINT NOT NULL AUTO_INCREMENT,
    login VARCHAR(150) NOT NULL,
    password VARCHAR(300) NOT NULL,
    role VARCHAR(50) NOT NULL,
    active TINYINT NOT NULL,

    PRIMARY KEY(id)
);